//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyOnlineBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks
    {
        public int IdMark { get; set; }
        public int UserId { get; set; }
        public int TaskId { get; set; }
        public Nullable<int> MarkValue { get; set; }
    
        public virtual Tasks Tasks { get; set; }
        public virtual Users Users { get; set; }
    }
}
